/// Event models for the EvenHub container system.
///
/// These events are generated by the glasses when the user interacts
/// with EvenHub containers (taps, scrolls) or when system events occur.

/// Source of a touch event on the glasses.
enum TouchSource {
  /// No touch source (system event).
  none(0),

  /// Right side of glasses touchpad.
  glassesRight(1),

  /// Ring controller.
  ring(2),

  /// Left side of glasses touchpad.
  glassesLeft(3);

  final int value;
  const TouchSource(this.value);

  static TouchSource fromValue(int v) {
    return TouchSource.values.firstWhere(
      (s) => s.value == v,
      orElse: () => TouchSource.none,
    );
  }
}

/// Types of EvenHub events from the glasses.
enum HubEventType {
  /// Single click/tap on a container.
  click(0),

  /// Scroll up gesture.
  scrollTop(1),

  /// Scroll down gesture.
  scrollBottom(2),

  /// Double click/tap on a container.
  doubleClick(3),

  /// EvenHub page entered foreground.
  foregroundEnter(4),

  /// EvenHub page exited foreground.
  foregroundExit(5),

  /// Abnormal exit (crash or error).
  abnormalExit(6),

  /// System-initiated exit.
  systemExit(7),

  /// IMU sensor data packet.
  imuData(8);

  final int value;
  const HubEventType(this.value);

  static HubEventType fromValue(int v) {
    return HubEventType.values.firstWhere(
      (t) => t.value == v,
      orElse: () => HubEventType.click,
    );
  }
}

/// An event from the EvenHub container system.
///
/// ```dart
/// g2.hub.events.listen((event) {
///   if (event.isClick) print('Clicked container ${event.containerID}');
///   if (event.isScroll) print('Scrolled');
///   if (event.isFromRight) print('From right touchpad');
/// });
/// ```
class HubEvent {
  /// The type of event.
  final HubEventType type;

  /// The touch source that generated this event.
  final TouchSource source;

  /// ID of the container that was interacted with (if applicable).
  final int? containerID;

  /// Name of the container that was interacted with (if applicable).
  final String? containerName;

  /// Index of the selected item in a list container (if applicable).
  final int? selectedItemIndex;

  /// Name of the selected item in a list container (if applicable).
  final String? selectedItemName;

  /// IMU sensor data (only for [HubEventType.imuData] events).
  final ImuData? imuData;

  HubEvent({
    required this.type,
    this.source = TouchSource.none,
    this.containerID,
    this.containerName,
    this.selectedItemIndex,
    this.selectedItemName,
    this.imuData,
  });

  // Convenience getters

  /// Whether this is a click event.
  bool get isClick => type == HubEventType.click;

  /// Whether this is a scroll event (up or down).
  bool get isScroll => type == HubEventType.scrollTop || type == HubEventType.scrollBottom;

  /// Whether this is a double click event.
  bool get isDoubleClick => type == HubEventType.doubleClick;

  /// Whether the event came from the left touchpad.
  bool get isFromLeft => source == TouchSource.glassesLeft;

  /// Whether the event came from the right touchpad.
  bool get isFromRight => source == TouchSource.glassesRight;

  /// Whether the event came from the ring controller.
  bool get isFromRing => source == TouchSource.ring;

  @override
  String toString() {
    final parts = ['HubEvent(${type.name}'];
    if (source != TouchSource.none) parts.add(' src=${source.name}');
    if (containerID != null) parts.add(' cid=$containerID');
    if (containerName != null) parts.add(' name=$containerName');
    if (selectedItemIndex != null) parts.add(' item=$selectedItemIndex');
    return '${parts.join()})';
  }
}

/// IMU (Inertial Measurement Unit) sensor data from the glasses.
class ImuData {
  /// X-axis value.
  final double x;

  /// Y-axis value.
  final double y;

  /// Z-axis value.
  final double z;

  ImuData({required this.x, required this.y, required this.z});

  @override
  String toString() => 'ImuData(x=$x, y=$y, z=$z)';
}
